text = input("Enter the text:")
text = text.lower()
text = text.replace("!","")
text = text.replace(".","")
text = text.replace(",","")
text = text.split()
unique = set(text)
result = " ".join(unique)
print(result)
